//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVENTURER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADVENTURER()
        {
            this.LORDs = new HashSet<LORD>();
            this.LORDs1 = new HashSet<LORD>();
        }
    
        public decimal ADVENTURERID { get; set; }
        public string NAME { get; set; }
        public decimal ENTITYID { get; set; }
        public decimal DUNGEONID { get; set; }
        public decimal SHOPID { get; set; }
    
        public virtual DUNGEON DUNGEON { get; set; }
        public virtual ENTITY ENTITY { get; set; }
        public virtual INVENTORY INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LORD> LORDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LORD> LORDs1 { get; set; }
    }
}
