//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.SLOTs = new HashSet<SLOT>();
        }
    
        public decimal ITEMID { get; set; }
        public decimal TYPEID { get; set; }
        public decimal PRICE { get; set; }
        public long ROOMSTOEQUIP { get; set; }
        public Nullable<byte> BONUSHEALTH { get; set; }
        public Nullable<byte> BONUSDEFENSE { get; set; }
        public Nullable<byte> BONUSATTACK { get; set; }
        public Nullable<byte> BONUSCRITICAL { get; set; }
    
        public virtual ITEMTYPE ITEMTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLOT> SLOTs { get; set; }
    }
}
