//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LORD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LORD()
        {
            this.ADVENTURERs = new HashSet<ADVENTURER>();
        }
    
        public decimal LORDID { get; set; }
        public string LOGIN { get; set; }
        public string PWD { get; set; }
        public bool BLOCKED { get; set; }
        public Nullable<decimal> CURRENTADVENTURER { get; set; }
    
        public virtual ADVENTURER ADVENTURER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVENTURER> ADVENTURERs { get; set; }
    }
}
