//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLOT
    {
        public decimal SLOTID { get; set; }
        public decimal INVENTORYID { get; set; }
        public decimal ITEMID { get; set; }
    
        public virtual INVENTORY INVENTORY { get; set; }
        public virtual ITEM ITEM { get; set; }
    }
}
